PRAGMA page_size=4096;
PRAGMA journal_mode=DELETE;
PRAGMA synchronous=FULL;
PRAGMA foreign_keys=ON;
PRAGMA application_id=1313555282;
PRAGMA user_version=1;
CREATE TABLE metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL) WITHOUT ROWID;
CREATE TABLE dataset(id TEXT PRIMARY KEY,source TEXT NOT NULL,records INTEGER NOT NULL) WITHOUT ROWID;
CREATE TABLE feature(id INTEGER PRIMARY KEY,dataset TEXT NOT NULL REFERENCES dataset(id),source_id TEXT NOT NULL,geometry TEXT NOT NULL,properties TEXT NOT NULL,min_x REAL NOT NULL,max_x REAL NOT NULL,min_y REAL NOT NULL,max_y REAL NOT NULL,UNIQUE(dataset,source_id));
CREATE INDEX feature_source ON feature(source_id);
CREATE VIRTUAL TABLE feature_bounds USING rtree(id,min_x,max_x,min_y,max_y);
CREATE TABLE feature_language(feature_id INTEGER NOT NULL REFERENCES feature(id),language TEXT NOT NULL,properties TEXT NOT NULL,PRIMARY KEY(feature_id,language)) WITHOUT ROWID;
CREATE TABLE search_row(id INTEGER PRIMARY KEY,language TEXT NOT NULL,ordinal INTEGER NOT NULL,source_key TEXT NOT NULL,name TEXT NOT NULL,query_text TEXT NOT NULL,kind TEXT NOT NULL,category TEXT NOT NULL,longitude REAL NOT NULL,latitude REAL NOT NULL,primary_text TEXT NOT NULL,all_text TEXT NOT NULL,primary_name TEXT NOT NULL,all_names TEXT NOT NULL,intent TEXT NOT NULL,phonetic TEXT NOT NULL,dedup_key TEXT NOT NULL,source_properties TEXT NOT NULL,UNIQUE(language,ordinal));
CREATE INDEX search_source ON search_row(source_key,language);
CREATE TABLE search_feature(search_id INTEGER NOT NULL REFERENCES search_row(id),feature_id INTEGER NOT NULL REFERENCES feature(id),PRIMARY KEY(search_id,feature_id)) WITHOUT ROWID;
CREATE TABLE posting(language TEXT NOT NULL,type TEXT NOT NULL,key TEXT NOT NULL,search_id INTEGER NOT NULL REFERENCES search_row(id),PRIMARY KEY(language,type,key,search_id)) WITHOUT ROWID;
CREATE TABLE lexeme(id INTEGER PRIMARY KEY,word TEXT NOT NULL UNIQUE,length INTEGER NOT NULL);
CREATE TABLE lexeme_gram(gram TEXT NOT NULL,lexeme_id INTEGER NOT NULL REFERENCES lexeme(id),PRIMARY KEY(gram,lexeme_id)) WITHOUT ROWID;
CREATE TABLE lexeme_posting(language TEXT NOT NULL,lexeme_id INTEGER NOT NULL REFERENCES lexeme(id),search_id INTEGER NOT NULL REFERENCES search_row(id),PRIMARY KEY(language,lexeme_id,search_id)) WITHOUT ROWID;
CREATE TABLE bk_edge(parent INTEGER NOT NULL REFERENCES lexeme(id),distance INTEGER NOT NULL,child INTEGER NOT NULL REFERENCES lexeme(id),PRIMARY KEY(parent,distance)) WITHOUT ROWID;
