-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class com.pichillilorenzo.flutter_inappwebview_android.** { *; }
-dontwarn org.chromium.**
-dontwarn com.google.android.play.core.**
